// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PZ.Data;

#nullable disable

namespace PriscilaZunigaWebBookBites.Migrations
{
    [DbContext(typeof(BookBitesContext))]
    partial class BookBitesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PriscilaZunigaWebBookBites.Models.PZCopia", b =>
                {
                    b.Property<int>("PZCopiaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PZCopiaID"));

                    b.Property<int>("PZCantidad")
                        .HasColumnType("int");

                    b.Property<bool>("PZColor")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PZFechaCopia")
                        .HasColumnType("date");

                    b.Property<string>("PZFormato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PZLibroID")
                        .HasColumnType("int");

                    b.HasKey("PZCopiaID");

                    b.HasIndex("PZLibroID");

                    b.ToTable("PZCopia");
                });

            modelBuilder.Entity("PriscilaZunigaWebBookBites.Models.PZLibro", b =>
                {
                    b.Property<int>("PZLibroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PZLibroID"));

                    b.Property<string>("PZAutor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PZNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PZPrecio")
                        .HasColumnType("real");

                    b.Property<string>("PZTitulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PZVolumen")
                        .HasColumnType("int");

                    b.HasKey("PZLibroID");

                    b.ToTable("PZLibro");
                });

            modelBuilder.Entity("PriscilaZunigaWebBookBites.Models.PZCopia", b =>
                {
                    b.HasOne("PriscilaZunigaWebBookBites.Models.PZLibro", "PZLibro")
                        .WithMany("PZCopia")
                        .HasForeignKey("PZLibroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PZLibro");
                });

            modelBuilder.Entity("PriscilaZunigaWebBookBites.Models.PZLibro", b =>
                {
                    b.Navigation("PZCopia");
                });
#pragma warning restore 612, 618
        }
    }
}
